feat: buttons,cards
ddivyansh18/Nyce-UI pull request #2
Opened 2022-02-01 08:42 UTC by ddivyansh18

Added buttons and cards to component library

2022-02-01 09:08 UTC, anuj-kumary requested changes
Some suggestions on your card component.
- like button style is not that attractive give some padding 
- Increase a little bit width of every card so it looks clean
- In horizontal card add an icon below your content so it looks NYC

2022-02-01 09:22 UTC, shrey27 approved these changes

2022-02-01 10:20 UTC, ddivyansh18 commented
@anuj-kumary I have made the requested changes, please approve or give additional feedbacks.

2022-02-02 08:15 UTC, anuj-kumary approved these changes

2022-02-02 08:16 UTC, merged